### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sanguivore-easyco** [Derfuu/Derfuu_ComfyUI_ModdedNodes#19]
Mind adding a license to the repo? My personal preference would be MIT, but there are plenty of options.

**Comment by Derfuu** [comment]
Not planned to add any licenses. If you want to use it or make something you want from it - be free to do it\copy it. But if it really needs one - maybe i'll add WTFPL. Don't have any knowledge about any other.

**Comment by sanguivore-easyco** [comment]
> Not planned to add any licenses. If you want to use it or make something you want from it - be free to do it\copy it. But if it really needs one - maybe i'll add WTFPL. Don't have any knowledge about any other.

Ha, I love WTFPL too! I'm not a lawyer, so I don't know if this conversation ends up basically serving the purpose or not. But I feel like I can use it in good faith given your response :)
