### ISSUE TITLE
Image and Latent outputs are backwards

### ISSUE THREAD

**Issue by Maveth** [Derfuu/Derfuu_ComfyUI_ModdedNodes#2]
Output are listed as INT,INT,TUPLE
If you connect debug prints, its actually TUPLE, INT, INT 
eg: output

FIRST: (384, 768)
SECOND: 384
THIRD: 768

FIX:
change:
RETURN_TYPES = ("INT", "INT", "TUPLE",)
to:
RETURN_TYPES = ("TUPLE", "INT", "INT", )

**Comment by Derfuu** [comment]
Fixed in last commit (~4 days ago) to:

```python
 #  LATENT
    ...
    def get_size(self, latent, original):
        size = sizes.get_latent_size(latent, original)
        return (size[0], size[1], size,)
    ...

 #  IMAGE
    ...
    def get_size(self, image):
        size = sizes.get_image_size(image)
        return (size[0], size[1], size, )
    ...
``` 

Please replace nodes in workflow if not work
