### ISSUE TITLE
Scale to Side Error

### ISSUE THREAD

**Issue by formulake** [Derfuu/Derfuu_ComfyUI_ModdedNodes#20]
Something seems to have broken with the recent mod to the scale-to-side node. It now throws up this error:

> Error occurred when executing Image scale to side:
> 
> Input and output sizes should be greater than 0, but got input (H: 675, W: 450) output (H: 0, W: 0)
> 
> File "F:\Tools\ComfyUI\execution.py", line 151, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "F:\Tools\ComfyUI\execution.py", line 81, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "F:\Tools\ComfyUI\execution.py", line 74, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "F:\Tools\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes\Nodes\Modded\StandardInputs\Images.py", line 106, in upscale
> cls = comfy.utils.common_upscale(samples, width, height, upscale_method, crop)
> File "F:\Tools\ComfyUI\comfy\utils.py", line 422, in common_upscale
> return torch.nn.functional.interpolate(s, size=(height, width), mode=upscale_method)
> File "F:\Tools\ComfyUI\venv\lib\site-packages\torch\nn\functional.py", line 4038, in interpolate
> return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)

**Comment by Derfuu** [comment]
Should be fixed with last commit.

**Comment by formulake** [comment]
Works perfectly. Thanks a ton!
