### ISSUE TITLE
"Int debug print" node is missing

### ISSUE THREAD

**Issue by KannManMachen** [Derfuu/Derfuu_ComfyUI_ModdedNodes#21]
Hey there :),

I loaded a custom workflow ( [https://pastebin.com/Zib4pxVD](https://pastebin.com/Zib4pxVD) ) which made use of `Derfuu_ComfyUI_ModdedNodes`. I installed the nodes via Manager. Somehow the `Int debug print` node is missing.

Cheers <3

**Comment by Derfuu** [comment]
Replace it with "To text (Debug)" node. Located in Derfuu_Nodes -> Debug -> To text (Debug). After last commits i replaced all debug nodes with single one, which containing text field widget to show the input value. Also it could return input value (same type as input, but can connect to any other) if you need to set it in-line.
