### ISSUE TITLE
Extension broken since the last update

### ISSUE THREAD

**Issue by Djanghost** [Derfuu/Derfuu_ComfyUI_ModdedNodes#23]
All the Derfuu_ComfyUI_ModdedNodes nodes are RED in ComfyUI since the last update. Impossible to use them.

**Comment by niko2020** [comment]
same here
how to update without loosing workflow data?

**Comment by Derfuu** [comment]
> All the Derfuu_ComfyUI_ModdedNodes nodes are RED in ComfyUI since the last update. Impossible to use them.

last updates i changed all nodes mappings to avoid different nodes classes conflicts (As comfyLiterals "Float" and other mapping names).

> same here how to update without loosing workflow data?

currently i don't know any other ways to do it, but roll back to [588f4cc](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/tree/588f4ccbe2169298099e1578f6ff0d4b56d90cf8)
or manually scroll through saved workflow.json file and replace all nodes "type" occurrences to new ones (like DF_node_name).

like this "type"
```json
"id": 31,
"type": "Text box",
```
to this
```json
"id": 31,
"type": "DF_Text_Box", 
```
and so on.

Sorry about that.

**Comment by yotraxxx** [comment]
Hi Derfuu,

Same issue here. Manually rolled back to https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/tree/588f4ccbe2169298099e1578f6ff0d4b56d90cf8 (zip download) solved it.

Thank you for your work in any case :)

**Comment by niko2020** [comment]
> ```json
> DF_Text_Box
> ```

Thank you, where can we find the mapping to replace for all the nodes?
Cheers

**Comment by Derfuu** [comment]
> > ```json
> > DF_Text_Box
> > ```
> 
> Thank you, where can we find the mapping to replace for all the nodes? Cheers

Current mappings are here: [\_\_init\_\_.py](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/blob/master/__init__.py) in repo root folder.

There's basically appending "DF_" and underscores instead of spaces to all strings inside NODE_CLASS_MAPPINGS dictionary. Previous mappings are here: [\_\_init\_\_.py](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/blob/588f4ccbe2169298099e1578f6ff0d4b56d90cf8/__init__.py)

Will do py script for replace them in json file as soon as i can.

**Comment by niko2020** [comment]
> Will do py script for replace them in json file as soon as i can.
[replace_values_in_json.py.txt](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/files/15107331/replace_values_in_json.py.txt)

**Comment by Derfuu** [comment]
Well. Looks like i'm a bit late with that. [utility/mapping_replace.py](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/blob/master/utility/mapping_replace.py)

**Comment by HWiese1980** [comment]
Is this automatic replacement now, or do I still have to do something manually?

**Comment by Derfuu** [comment]
> Is this automatic replacement now, or do I still have to do something manually?

You need launch this script from your python environment (also you need "json" library installed in this environment) and enter path to workflow.json file in console, where replace old mapping. Edited file will be in "replaced" folder near this script.

**Comment by HWiese1980** [comment]
Okay. For curiosity, what's the reason that you renamed the nodes? Were the original names too common?

**Comment by Derfuu** [comment]
Some of them - yes, some of them - no. As i mentioned earlier:

> last updates i changed all nodes mappings to avoid different nodes classes conflicts (As comfyLiterals "Float" and other mapping names).

I decided to rename mappings in advance to avoid this issue in future and people who used that nodes could differ them from each other, if anyone else will make nodes with similar mapping names.

like there:
![image](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/54149748/bfdd4e8d-3f04-4194-9de1-5e27795ec362)

**Comment by HWiese1980** [comment]
Understood. Makes sense.

**Comment by wes-kay** [comment]
I have no clue what's going on here. It's an absolute mess. I don't know why this module is even included in my workflow and I've spent an hour on it so far trying to deal with it.

Look into args parse, there's no reason to use a mapping to a json file to replace strings here. This is all basic python standards.

**Comment by HWiese1980** [comment]
@wes-kay Are you a software engineer? I am. Derfuu might not be. Expectation management, dude. Constructive criticism!

**Comment by wes-kay** [comment]
> @wes-kay Are you a software engineer? I am. Derfuu might not be. Expectation management, dude. Constructive criticism!

Yes I am, so far I've spent 2 hours trying to remove this module from a workflow I've spent months creating because it looks like it's been generated by GPT without any understanding of python or production standards.
![image](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/40011470/edea638d-f131-45c9-90c3-8130261f3e88)

My constructive criticism is learn basic standards in development. You don't need to be a SE to know what args are and even more so you shouldn't be breaking everyone's workflows, make a NEW plugin and update the readme, have the users decide if they want to update.

**Comment by Djanghost** [comment]
For my part, with the command "git reset --hard" I reinstalled the node that was working before the bad update and saved it in a folder. Every time I update Comfy and its extension nodes, I just copy/paste the good previous version into my extension node folder, deleting the new one. This way i can keep all my previous workflows working. 
I'm not a dev, so I don't really understand why Derfuu doesn't simply revert to the previous version, it would be much better for everyone.
