### ISSUE TITLE
Not compatibe with Python <3.10

### ISSUE THREAD

**Issue by mamorn** [Derfuu/Derfuu_ComfyUI_ModdedNodes#3]
Hey there! So I was attempting to use these nodes in colab with the notebook from comfyanon, but I ran into an issue with the switch case used in tuples because colab is on Python 3.9. Do you think we could switch it up to use elif instead? That way, it'd work with older Python versions too.

**Comment by Derfuu** [comment]
Updated, should now work on py 3.9. Please test it, cause i don't use colab for it

**Comment by mamorn** [comment]
Hey, yep it seems to work fine. There are no errors at runtime but I've only tried a few of the nodes. Mainly the ones under function and variables. I guess I'll close the issue. Thank you so much for the quick response and fix.
