### ISSUE TITLE
Variable Node Integer is not INT but FLOAT

### ISSUE THREAD

**Issue by seedlord** [Derfuu/Derfuu_ComfyUI_ModdedNodes#6]
In Nodes\Custom\Types.py
the integer variable is a float.
for fix replace 

```
                "Value": ("FLOAT", {
                        "default": 1,
                        "min": -sys.float_info.max,
                        "max": sys.float_info.max,
```

with

```
                "Value": ("INT", {
                        "default": 1,
                        "min": -sys.maxsize,
                        "max": sys.maxsize,
```

**Comment by seedlord** [comment]
Another Issue i found is in Nodes\Functions\GetSizes.py
the Tuple output for Node GetLatentSize is mixed up.
for fix replace 
```
    RETURN_TYPES = ("INT", "INT", "TUPLE",)
```

with

```
    RETURN_TYPES = ("TUPLE", "INT", "INT")
```

**Comment by Derfuu** [comment]
> Another Issue i found is in Nodes\Functions\GetSizes.py the Tuple output for Node GetLatentSize is mixed up. for fix replace
> 
> ```
>     RETURN_TYPES = ("INT", "INT", "TUPLE",)
> ```
> 
> with
> 
> ```
>     RETURN_TYPES = ("TUPLE", "INT", "INT")
> ```
Didn't notice that they are mixed.

And this one should be fixed now.
> In Nodes\Custom\Types.py the integer variable is a float. for fix replace
> 
> ```
>                 "Value": ("FLOAT", {
>                         "default": 1,
>                         "min": -sys.float_info.max,
>                         "max": sys.float_info.max,
> ```
> 
> with
> 
> ```
>                 "Value": ("INT", {
>                         "default": 1,
>                         "min": -sys.maxsize,
>                         "max": sys.maxsize,
> ```

Close this issue for now. If i'm really messed with output for latent GetSize node - open a new one.
